# Generated by Django 2.0.5 on 2018-07-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180708_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-uploaded_at',)},
        ),
    ]
