# Generated by Django 2.0.5 on 2018-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180709_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
